# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: bralegz
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs-api

useDotenv: true

# We add the environment provider to preload the environment variables.
provider:
  name: aws
  runtime: nodejs22.x
  environment:
    DEBUG: ${env:DEBUG, 0}
    DATABASE_URL: ${env:DATABASE_URL}
  iam:
    role:
      name: serverless-ssm-role
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:GetParametersByPath"
            - "ssm:GetParameterHistory"
            - "ssm:DescribeParameters"

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

custom: 
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL

plugins:
  - serverless-offline
  - serverless-dotenv-plugin